sudo: required
services:
    - docker

before_install:
    - docker build -t vkishorekumar80/docker-react -f Dockerfile.dev

script:
    - docker run -e CI=true vkishorekumar80/docker-react npm run test